# Makefile
#

BYTES_C = ~/programming/computersystems-exercises/bytes/bytes.c
BYTES_H = ~/programming/computersystems-exercises/bytes/bytes.h


shifts.out: shifts.c ${BYTES_C} ${BYTES_H}
	gcc -g -Wall -pedantic -o shifts.out shifts.c ${BYTES_C}
